// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9PZNDt33Etdws9wo_-AalEsWmRpgTAQk',
    appId: '1:177278539631:web:24b163d65520e81d6c7a9a',
    messagingSenderId: '177278539631',
    projectId: 'dysignager',
    authDomain: 'dysignager.firebaseapp.com',
    databaseURL: 'https://dysignager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dysignager.appspot.com',
    measurementId: 'G-LEJK147YGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRzVlHSStyQYIL2Bk_u0AveesooZVG28',
    appId: '1:177278539631:android:34cb0af9e219feae6c7a9a',
    messagingSenderId: '177278539631',
    projectId: 'dysignager',
    databaseURL: 'https://dysignager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dysignager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyhgOMeRABiTeFeAp6uicWoYL2329ldTg',
    appId: '1:177278539631:ios:fcff97ab877d96166c7a9a',
    messagingSenderId: '177278539631',
    projectId: 'dysignager',
    databaseURL: 'https://dysignager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dysignager.appspot.com',
    iosClientId: '177278539631-25lhemn0knhcvn4nl103d9o4c46tbgi4.apps.googleusercontent.com',
    iosBundleId: 'com.digi.billboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyhgOMeRABiTeFeAp6uicWoYL2329ldTg',
    appId: '1:177278539631:ios:89c25b60bdbd00506c7a9a',
    messagingSenderId: '177278539631',
    projectId: 'dysignager',
    databaseURL: 'https://dysignager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dysignager.appspot.com',
    iosClientId: '177278539631-4beblug5up204a8g3uranflegjmodf3l.apps.googleusercontent.com',
    iosBundleId: 'com.digi.billboard.RunnerTests',
  );
}
